CC=gcc
CFLAGS=-g -std=c11 -pedantic -Wall -Wextra

all: htab_hash_function.c htab_init.c test_htab.c htab_item_init.c htab_insert_item.c htab_erase.c htab_clear.c
	$(CC) $(CFLAGS) htab_hash_function.c htab_init.c test_htab.c htab_item_init.c htab_insert_item.c htab_erase.c htab_clear.c -o testing